version: "3.8"

services:
  postgres:
    container_name: car-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - car-network-prod
    restart: unless-stopped

  minio:
    container_name: car-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    volumes:
      - minio_data_prod:/data
    networks:
      - car-network-prod
    restart: unless-stopped

  redis:
    container_name: car-redis
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data_prod:/data
    networks:
      - car-network-prod
    restart: unless-stopped

  redis-commander:
    container_name: car-redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:car-redis:6379:0
    depends_on:
      - redis
    networks:
      - car-network-prod
    restart: unless-stopped

  car-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-api
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      PORT: ${PORT}
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - car-network-prod
    restart: unless-stopped

  car-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-web
    ports:
      - "8080:80"
    networks:
      - car-network-prod
    restart: unless-stopped

  car-crm:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-crm
    ports:
      - "8081:80"
    networks:
      - car-network-prod
    restart: unless-stopped

networks:
  car-network-prod:
    driver: bridge

volumes:
  postgres_data_prod:
  redis_data_prod:
  minio_data_prod:
