/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header/AppHeader.vue')['default']
    AutoLoanCalculator: typeof import('./src/components/auto-loan/AutoLoanCalculator.vue')['default']
    AutoLoanModal: typeof import('./src/components/auto-loan/AutoLoanModal.vue')['default']
    PhotoSlider: typeof import('./src/components/PhotoSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestDriveModal: typeof import('./src/components/test-drive/TestDriveModal.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
