/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/app-sidebar/AppSidebar.vue')['default']
    Button: typeof import('primevue/button')['default']
    ConfigurationList: typeof import('./src/components/configurations/ConfigurationList.vue')['default']
    ConfigurationModal: typeof import('./src/components/configurations/ConfigurationModal.vue')['default']
    ModelCard: typeof import('./src/components/models/ModelCard.vue')['default']
    ModelModal: typeof import('./src/components/models/ModelModal.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    PhotoSlider: typeof import('./src/components/PhotoSlider.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarSettings: typeof import('./src/components/app-sidebar/SidebarSettings.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
